export const SURAH_RUKU_MAP = [
  { surahNum: 1, name: "Al-Fatiha", rakuCount: 1, startRaku: 1, endRaku: 1 },
  { surahNum: 2, name: "Al-Baqarah", rakuCount: 40, startRaku: 2, endRaku: 41 },
  { surahNum: 3, name: "Al-Imran", rakuCount: 20, startRaku: 42, endRaku: 61 },
  { surahNum: 4, name: "An-Nisa", rakuCount: 24, startRaku: 62, endRaku: 85 },
  { surahNum: 5, name: "Al-Ma'idah", rakuCount: 16, startRaku: 86, endRaku: 101 },
  { surahNum: 6, name: "Al-An'am", rakuCount: 20, startRaku: 102, endRaku: 121 },
  { surahNum: 7, name: "Al-A'raf", rakuCount: 24, startRaku: 122, endRaku: 145 },
  { surahNum: 8, name: "Al-Anfal", rakuCount: 10, startRaku: 146, endRaku: 155 },
  { surahNum: 9, name: "At-Tawbah", rakuCount: 16, startRaku: 156, endRaku: 171 },
  { surahNum: 10, name: "Yunus", rakuCount: 11, startRaku: 172, endRaku: 182 },
  { surahNum: 11, name: "Hud", rakuCount: 10, startRaku: 183, endRaku: 192 },
  { surahNum: 12, name: "Yusuf", rakuCount: 12, startRaku: 193, endRaku: 204 },
  { surahNum: 13, name: "Ar-Ra'd", rakuCount: 6, startRaku: 205, endRaku: 210 },
  { surahNum: 14, name: "Ibrahim", rakuCount: 7, startRaku: 211, endRaku: 217 },
  { surahNum: 15, name: "Al-Hijr", rakuCount: 6, startRaku: 218, endRaku: 223 },
  { surahNum: 16, name: "An-Nahl", rakuCount: 17, startRaku: 224, endRaku: 240 },
  { surahNum: 17, name: "Al-Isra", rakuCount: 12, startRaku: 241, endRaku: 252 },
  { surahNum: 18, name: "Al-Kahf", rakuCount: 12, startRaku: 253, endRaku: 264 },
  { surahNum: 19, name: "Maryam", rakuCount: 6, startRaku: 265, endRaku: 270 },
  { surahNum: 20, name: "Ta-Ha", rakuCount: 8, startRaku: 271, endRaku: 278 },
  { surahNum: 21, name: "Al-Anbiya", rakuCount: 7, startRaku: 279, endRaku: 285 },
  { surahNum: 22, name: "Al-Hajj", rakuCount: 10, startRaku: 286, endRaku: 295 },
  { surahNum: 23, name: "Al-Mu'minun", rakuCount: 6, startRaku: 296, endRaku: 301 },
  { surahNum: 24, name: "An-Nur", rakuCount: 10, startRaku: 302, endRaku: 311 },
  { surahNum: 25, name: "Al-Furqan", rakuCount: 6, startRaku: 312, endRaku: 317 },
  { surahNum: 26, name: "Ash-Shu'ara", rakuCount: 6, startRaku: 318, endRaku: 323 },
  { surahNum: 27, name: "An-Naml", rakuCount: 5, startRaku: 324, endRaku: 328 },
  { surahNum: 28, name: "Al-Qasas", rakuCount: 8, startRaku: 329, endRaku: 336 },
  { surahNum: 29, name: "Al-Ankabut", rakuCount: 7, startRaku: 337, endRaku: 343 },
  { surahNum: 30, name: "Ar-Rum", rakuCount: 6, startRaku: 344, endRaku: 349 },
  { surahNum: 31, name: "Luqman", rakuCount: 4, startRaku: 350, endRaku: 353 },
  { surahNum: 32, name: "As-Sajdah", rakuCount: 4, startRaku: 354, endRaku: 357 },
  { surahNum: 33, name: "Al-Ahzab", rakuCount: 9, startRaku: 358, endRaku: 366 },
  { surahNum: 34, name: "Saba", rakuCount: 6, startRaku: 367, endRaku: 372 },
  { surahNum: 35, name: "Fatir", rakuCount: 5, startRaku: 373, endRaku: 377 },
  { surahNum: 36, name: "Ya-Sin", rakuCount: 5, startRaku: 378, endRaku: 382 },
  { surahNum: 37, name: "As-Saffat", rakuCount: 5, startRaku: 383, endRaku: 387 },
  { surahNum: 38, name: "Sad", rakuCount: 5, startRaku: 388, endRaku: 392 },
  { surahNum: 39, name: "Az-Zumar", rakuCount: 8, startRaku: 393, endRaku: 400 },
  { surahNum: 40, name: "Ghafir", rakuCount: 9, startRaku: 401, endRaku: 409 },
  { surahNum: 41, name: "Fussilat", rakuCount: 6, startRaku: 410, endRaku: 415 },
  { surahNum: 42, name: "Ash-Shura", rakuCount: 5, startRaku: 416, endRaku: 420 },
  { surahNum: 43, name: "Az-Zukhruf", rakuCount: 7, startRaku: 421, endRaku: 427 },
  { surahNum: 44, name: "Ad-Dukhan", rakuCount: 4, startRaku: 428, endRaku: 431 },
  { surahNum: 45, name: "Al-Jathiyah", rakuCount: 4, startRaku: 432, endRaku: 435 },
  { surahNum: 46, name: "Al-Ahqaf", rakuCount: 4, startRaku: 436, endRaku: 439 },
  { surahNum: 47, name: "Muhammad", rakuCount: 4, startRaku: 440, endRaku: 443 },
  { surahNum: 48, name: "Al-Fath", rakuCount: 4, startRaku: 444, endRaku: 447 },
  { surahNum: 49, name: "Al-Hujurat", rakuCount: 4, startRaku: 448, endRaku: 451 },
  { surahNum: 50, name: "Qaf", rakuCount: 3, startRaku: 452, endRaku: 454 },
  { surahNum: 51, name: "Adh-Dhariyat", rakuCount: 3, startRaku: 455, endRaku: 457 },
  { surahNum: 52, name: "At-Tur", rakuCount: 3, startRaku: 458, endRaku: 460 },
  { surahNum: 53, name: "An-Najm", rakuCount: 3, startRaku: 461, endRaku: 463 },
  { surahNum: 54, name: "Al-Qamar", rakuCount: 3, startRaku: 464, endRaku: 466 },
  { surahNum: 55, name: "Ar-Rahman", rakuCount: 3, startRaku: 467, endRaku: 469 },
  { surahNum: 56, name: "Al-Waqi'ah", rakuCount: 3, startRaku: 470, endRaku: 472 },
  { surahNum: 57, name: "Al-Hadid", rakuCount: 4, startRaku: 473, endRaku: 476 },
  { surahNum: 58, name: "Al-Mujadila", rakuCount: 4, startRaku: 477, endRaku: 480 },
  { surahNum: 59, name: "Al-Hashr", rakuCount: 3, startRaku: 481, endRaku: 483 },
  { surahNum: 60, name: "Al-Mumtahanah", rakuCount: 2, startRaku: 484, endRaku: 485 },
  { surahNum: 61, name: "As-Saf", rakuCount: 2, startRaku: 486, endRaku: 487 },
  { surahNum: 62, name: "Al-Jumu'ah", rakuCount: 2, startRaku: 488, endRaku: 489 },
  { surahNum: 63, name: "Al-Munafiqun", rakuCount: 2, startRaku: 490, endRaku: 491 },
  { surahNum: 64, name: "At-Taghabun", rakuCount: 2, startRaku: 492, endRaku: 493 },
  { surahNum: 65, name: "At-Talaq", rakuCount: 2, startRaku: 494, endRaku: 495 },
  { surahNum: 66, name: "At-Tahrim", rakuCount: 2, startRaku: 496, endRaku: 497 },
  { surahNum: 67, name: "Al-Mulk", rakuCount: 2, startRaku: 498, endRaku: 499 },
  { surahNum: 68, name: "Al-Qalam", rakuCount: 2, startRaku: 500, endRaku: 501 },
  { surahNum: 69, name: "Al-Haqqah", rakuCount: 2, startRaku: 502, endRaku: 503 },
  { surahNum: 70, name: "Al-Ma'arij", rakuCount: 2, startRaku: 504, endRaku: 505 },
  { surahNum: 71, name: "Nuh", rakuCount: 2, startRaku: 506, endRaku: 507 },
  { surahNum: 72, name: "Al-Jinn", rakuCount: 2, startRaku: 508, endRaku: 509 },
  { surahNum: 73, name: "Al-Muzzammil", rakuCount: 2, startRaku: 510, endRaku: 511 },
  { surahNum: 74, name: "Al-Muddaththir", rakuCount: 2, startRaku: 512, endRaku: 513 },
  { surahNum: 75, name: "Al-Qiyamah", rakuCount: 2, startRaku: 514, endRaku: 515 },
  { surahNum: 76, name: "Al-Insan", rakuCount: 2, startRaku: 516, endRaku: 517 },
  { surahNum: 77, name: "Al-Mursalat", rakuCount: 2, startRaku: 518, endRaku: 519 },
  { surahNum: 78, name: "An-Naba", rakuCount: 1, startRaku: 520, endRaku: 520 },
  { surahNum: 79, name: "An-Nazi'at", rakuCount: 2, startRaku: 521, endRaku: 522 },
  { surahNum: 80, name: "Abasa", rakuCount: 1, startRaku: 523, endRaku: 523 },
  { surahNum: 81, name: "At-Takwir", rakuCount: 1, startRaku: 524, endRaku: 524 },
  { surahNum: 82, name: "Al-Infitar", rakuCount: 1, startRaku: 525, endRaku: 525 },
  { surahNum: 83, name: "Al-Mutaffifin", rakuCount: 1, startRaku: 526, endRaku: 526 },
  { surahNum: 84, name: "Al-Inshiqaq", rakuCount: 1, startRaku: 527, endRaku: 527 },
  { surahNum: 85, name: "Al-Buruj", rakuCount: 1, startRaku: 528, endRaku: 528 },
  { surahNum: 86, name: "At-Tariq", rakuCount: 1, startRaku: 529, endRaku: 529 },
  { surahNum: 87, name: "Al-A'la", rakuCount: 1, startRaku: 530, endRaku: 530 },
  { surahNum: 88, name: "Al-Ghashiyah", rakuCount: 1, startRaku: 531, endRaku: 531 },
  { surahNum: 89, name: "Al-Fajr", rakuCount: 1, startRaku: 532, endRaku: 532 },
  { surahNum: 90, name: "Al-Balad", rakuCount: 1, startRaku: 533, endRaku: 533 },
  { surahNum: 91, name: "Ash-Shams", rakuCount: 1, startRaku: 534, endRaku: 534 },
  { surahNum: 92, name: "Al-Layl", rakuCount: 1, startRaku: 535, endRaku: 535 },
  { surahNum: 93, name: "Ad-Duha", rakuCount: 1, startRaku: 536, endRaku: 536 },
  { surahNum: 94, name: "Ash-Sharh", rakuCount: 1, startRaku: 537, endRaku: 537 },
  { surahNum: 95, name: "At-Tin", rakuCount: 1, startRaku: 538, endRaku: 538 },
  { surahNum: 96, name: "Al-Alaq", rakuCount: 1, startRaku: 539, endRaku: 539 },
  { surahNum: 97, name: "Al-Qadr", rakuCount: 1, startRaku: 540, endRaku: 540 },
  { surahNum: 98, name: "Al-Bayyinah", rakuCount: 1, startRaku: 541, endRaku: 541 },
  { surahNum: 99, name: "Az-Zalzalah", rakuCount: 1, startRaku: 542, endRaku: 542 },
  { surahNum: 100, name: "Al-Adiyat", rakuCount: 1, startRaku: 543, endRaku: 543 },
  { surahNum: 101, name: "Al-Qari'ah", rakuCount: 1, startRaku: 544, endRaku: 544 },
  { surahNum: 102, name: "At-Takathur", rakuCount: 1, startRaku: 545, endRaku: 545 },
  { surahNum: 103, name: "Al-Asr", rakuCount: 1, startRaku: 546, endRaku: 546 },
  { surahNum: 104, name: "Al-Humazah", rakuCount: 1, startRaku: 547, endRaku: 547 },
  { surahNum: 105, name: "Al-Fil", rakuCount: 1, startRaku: 548, endRaku: 548 },
  { surahNum: 106, name: "Quraysh", rakuCount: 1, startRaku: 549, endRaku: 549 },
  { surahNum: 107, name: "Al-Ma'un", rakuCount: 1, startRaku: 550, endRaku: 550 },
  { surahNum: 108, name: "Al-Kawthar", rakuCount: 1, startRaku: 551, endRaku: 551 },
  { surahNum: 109, name: "Al-Kafirun", rakuCount: 1, startRaku: 552, endRaku: 552 },
  { surahNum: 110, name: "An-Nasr", rakuCount: 1, startRaku: 553, endRaku: 553 },
  { surahNum: 111, name: "Al-Masad", rakuCount: 1, startRaku: 554, endRaku: 554 },
  { surahNum: 112, name: "Al-Ikhlas", rakuCount: 1, startRaku: 555, endRaku: 555 },
  { surahNum: 113, name: "Al-Falaq", rakuCount: 1, startRaku: 556, endRaku: 556 },
  { surahNum: 114, name: "An-Nas", rakuCount: 1, startRaku: 557, endRaku: 557 },
] as const;

export const TOTAL_RAKU = 557;

export function getSurahForRaku(rakuNum: number) {
  return SURAH_RUKU_MAP.find(
    (s) => rakuNum >= s.startRaku && rakuNum <= s.endRaku
  );
}

export function getRakuWithinSurah(rakuNum: number) {
  const surah = getSurahForRaku(rakuNum);
  if (!surah) return null;
  return rakuNum - surah.startRaku + 1;
}

// Juz 30 memorization order (back to front: An-Nas → Naba)
export const JUZ30_VERSES = [
  // An-Nas (114) - 6 verses
  { surahNum: 114, ayahNum: 1, arabic: "قُلْ أَعُوذُ بِرَبِّ النَّاسِ", transliteration: "Qul a'udhu bi-rabbi n-nas", translation: "Say: I seek refuge with the Lord of mankind" },
  { surahNum: 114, ayahNum: 2, arabic: "مَلِكِ النَّاسِ", transliteration: "Maliki n-nas", translation: "The King of mankind" },
  { surahNum: 114, ayahNum: 3, arabic: "إِلَٰهِ النَّاسِ", transliteration: "Ilahi n-nas", translation: "The God of mankind" },
  { surahNum: 114, ayahNum: 4, arabic: "مِن شَرِّ الْوَسْوَاسِ الْخَنَّاسِ", transliteration: "Min sharri l-waswasi l-khannās", translation: "From the evil of the retreating whisperer" },
  { surahNum: 114, ayahNum: 5, arabic: "الَّذِي يُوَسْوِسُ فِي صُدُورِ النَّاسِ", transliteration: "Alladhī yuwaswisu fī ṣudūri n-nās", translation: "Who whispers in the breasts of mankind" },
  { surahNum: 114, ayahNum: 6, arabic: "مِنَ الْجِنَّةِ وَالنَّاسِ", transliteration: "Mina l-jinnati wa n-nās", translation: "From among the jinn and mankind" },
  // Al-Falaq (113) - 5 verses
  { surahNum: 113, ayahNum: 1, arabic: "قُلْ أَعُوذُ بِرَبِّ الْفَلَقِ", transliteration: "Qul a'udhu bi-rabbi l-falaq", translation: "Say: I seek refuge with the Lord of the daybreak" },
  { surahNum: 113, ayahNum: 2, arabic: "مِن شَرِّ مَا خَلَقَ", transliteration: "Min sharri mā khalaq", translation: "From the evil of what He has created" },
  { surahNum: 113, ayahNum: 3, arabic: "وَمِن شَرِّ غَاسِقٍ إِذَا وَقَبَ", transliteration: "Wa min sharri ghāsiqin idhā waqab", translation: "And from the evil of the darkening night as it comes with its darkness" },
  { surahNum: 113, ayahNum: 4, arabic: "وَمِن شَرِّ النَّفَّاثَاتِ فِي الْعُقَدِ", transliteration: "Wa min sharri n-naffāthāti fi l-'uqad", translation: "And from the evil of those who blow on knots" },
  { surahNum: 113, ayahNum: 5, arabic: "وَمِن شَرِّ حَاسِدٍ إِذَا حَسَدَ", transliteration: "Wa min sharri ḥāsidin idhā ḥasad", translation: "And from the evil of the envier when he envies" },
  // Al-Ikhlas (112) - 4 verses
  { surahNum: 112, ayahNum: 1, arabic: "قُلْ هُوَ اللَّهُ أَحَدٌ", transliteration: "Qul huwa l-lāhu aḥad", translation: "Say: He is Allah, the One" },
  { surahNum: 112, ayahNum: 2, arabic: "اللَّهُ الصَّمَدُ", transliteration: "Allāhu ṣ-ṣamad", translation: "Allah, the Eternal Refuge" },
  { surahNum: 112, ayahNum: 3, arabic: "لَمْ يَلِدْ وَلَمْ يُولَدْ", transliteration: "Lam yalid wa lam yūlad", translation: "He neither begets nor is born" },
  { surahNum: 112, ayahNum: 4, arabic: "وَلَمْ يَكُن لَّهُ كُفُوًا أَحَدٌ", transliteration: "Wa lam yakun lahu kufuwan aḥad", translation: "Nor is there to Him any equivalent" },
  // Al-Masad (111) - 5 verses
  { surahNum: 111, ayahNum: 1, arabic: "تَبَّتْ يَدَا أَبِي لَهَبٍ وَتَبَّ", transliteration: "Tabbat yadā abī lahabin wa tabb", translation: "May the hands of Abu Lahab be ruined, and ruined is he" },
  { surahNum: 111, ayahNum: 2, arabic: "مَا أَغْنَىٰ عَنْهُ مَالُهُ وَمَا كَسَبَ", transliteration: "Mā aghnā 'anhu māluhu wa mā kasab", translation: "His wealth will not avail him or that which he gained" },
  { surahNum: 111, ayahNum: 3, arabic: "سَيَصْلَىٰ نَارًا ذَاتَ لَهَبٍ", transliteration: "Sayaṣlā nāran dhāta lahab", translation: "He will burn in a fire of blazing flame" },
  { surahNum: 111, ayahNum: 4, arabic: "وَامْرَأَتُهُ حَمَّالَةَ الْحَطَبِ", transliteration: "Wa mra'atuhu ḥammālata l-ḥaṭab", translation: "And his wife who carries firewood" },
  { surahNum: 111, ayahNum: 5, arabic: "فِي جِيدِهَا حَبْلٌ مِّن مَّسَدٍ", transliteration: "Fī jīdihā ḥablun min masad", translation: "Around her neck is a rope of palm fiber" },
  // An-Nasr (110) - 3 verses
  { surahNum: 110, ayahNum: 1, arabic: "إِذَا جَاءَ نَصْرُ اللَّهِ وَالْفَتْحُ", transliteration: "Idhā jā'a naṣru l-lāhi wa l-fatḥ", translation: "When the victory of Allah has come and the conquest" },
  { surahNum: 110, ayahNum: 2, arabic: "وَرَأَيْتَ النَّاسَ يَدْخُلُونَ فِي دِينِ اللَّهِ أَفْوَاجًا", transliteration: "Wa ra'ayta n-nāsa yadkhulūna fī dīni l-lāhi afwājā", translation: "And you see the people entering into the religion of Allah in multitudes" },
  { surahNum: 110, ayahNum: 3, arabic: "فَسَبِّحْ بِحَمْدِ رَبِّكَ وَاسْتَغْفِرْهُ ۚ إِنَّهُ كَانَ تَوَّابًا", transliteration: "Fasabbiḥ biḥamdi rabbika wa s-taghfirh, innahu kāna tawwābā", translation: "Then exalt Him with praise of your Lord and ask forgiveness of Him. Indeed, He is ever accepting of repentance" },
  // Al-Kafirun (109) - 6 verses
  { surahNum: 109, ayahNum: 1, arabic: "قُلْ يَا أَيُّهَا الْكَافِرُونَ", transliteration: "Qul yā ayyuhā l-kāfirūn", translation: "Say: O disbelievers" },
  { surahNum: 109, ayahNum: 2, arabic: "لَا أَعْبُدُ مَا تَعْبُدُونَ", transliteration: "Lā a'budu mā ta'budūn", translation: "I do not worship what you worship" },
  { surahNum: 109, ayahNum: 3, arabic: "وَلَا أَنتُمْ عَابِدُونَ مَا أَعْبُدُ", transliteration: "Wa lā antum 'ābidūna mā a'bud", translation: "Nor are you worshippers of what I worship" },
  { surahNum: 109, ayahNum: 4, arabic: "وَلَا أَنَا عَابِدٌ مَّا عَبَدتُّمْ", transliteration: "Wa lā anā 'ābidun mā 'abadttum", translation: "Nor will I be a worshipper of what you worship" },
  { surahNum: 109, ayahNum: 5, arabic: "وَلَا أَنتُمْ عَابِدُونَ مَا أَعْبُدُ", transliteration: "Wa lā antum 'ābidūna mā a'bud", translation: "Nor will you be worshippers of what I worship" },
  { surahNum: 109, ayahNum: 6, arabic: "لَكُمْ دِينُكُمْ وَلِيَ دِينِ", transliteration: "Lakum dīnukum wa liya dīn", translation: "For you is your religion, and for me is my religion" },
  // Al-Kawthar (108) - 3 verses
  { surahNum: 108, ayahNum: 1, arabic: "إِنَّا أَعْطَيْنَاكَ الْكَوْثَرَ", transliteration: "Innā a'ṭaynāka l-kawthar", translation: "Indeed, We have granted you al-Kawthar" },
  { surahNum: 108, ayahNum: 2, arabic: "فَصَلِّ لِرَبِّكَ وَانْحَرْ", transliteration: "Faṣalli li-rabbika wa nḥar", translation: "So pray to your Lord and sacrifice to Him" },
  { surahNum: 108, ayahNum: 3, arabic: "إِنَّ شَانِئَكَ هُوَ الْأَبْتَرُ", transliteration: "Inna shāni'aka huwa l-abtar", translation: "Indeed, your enemy is the one cut off" },
  // Al-Ma'un (107) - 7 verses
  { surahNum: 107, ayahNum: 1, arabic: "أَرَأَيْتَ الَّذِي يُكَذِّبُ بِالدِّينِ", transliteration: "Ara'ayta l-ladhī yukadhdhibu bi d-dīn", translation: "Have you seen the one who denies the Recompense?" },
  { surahNum: 107, ayahNum: 2, arabic: "فَذَٰلِكَ الَّذِي يَدُعُّ الْيَتِيمَ", transliteration: "Fa-dhālika l-ladhī yadu'u l-yatīm", translation: "For that is the one who drives away the orphan" },
  { surahNum: 107, ayahNum: 3, arabic: "وَلَا يَحُضُّ عَلَىٰ طَعَامِ الْمِسْكِينِ", transliteration: "Wa lā yaḥuḍḍu 'alā ṭa'āmi l-miskīn", translation: "And does not encourage the feeding of the poor" },
  { surahNum: 107, ayahNum: 4, arabic: "فَوَيْلٌ لِّلْمُصَلِّينَ", transliteration: "Fa-waylun li l-muṣallīn", translation: "So woe to those who pray" },
  { surahNum: 107, ayahNum: 5, arabic: "الَّذِينَ هُمْ عَن صَلَاتِهِمْ سَاهُونَ", transliteration: "Alladhīna hum 'an ṣalātihim sāhūn", translation: "Who are heedless of their prayer" },
  { surahNum: 107, ayahNum: 6, arabic: "الَّذِينَ هُمْ يُرَاءُونَ", transliteration: "Alladhīna hum yurā'ūn", translation: "Those who make show of their deeds" },
  { surahNum: 107, ayahNum: 7, arabic: "وَيَمْنَعُونَ الْمَاعُونَ", transliteration: "Wa yamna'ūna l-mā'ūn", translation: "And withhold simple assistance" },
  // Quraysh (106) - 4 verses
  { surahNum: 106, ayahNum: 1, arabic: "لِإِيلَافِ قُرَيْشٍ", transliteration: "Li-'ilāfi quraysh", translation: "For the accustomed security of the Quraysh" },
  { surahNum: 106, ayahNum: 2, arabic: "إِيلَافِهِمْ رِحْلَةَ الشِّتَاءِ وَالصَّيْفِ", transliteration: "Īlāfihim riḥlata sh-shitā'i wa ṣ-ṣayf", translation: "Their accustomed security in the journey of winter and summer" },
  { surahNum: 106, ayahNum: 3, arabic: "فَلْيَعْبُدُوا رَبَّ هَٰذَا الْبَيْتِ", transliteration: "Falya'budū rabba hādhā l-bayt", translation: "Let them worship the Lord of this House" },
  { surahNum: 106, ayahNum: 4, arabic: "الَّذِي أَطْعَمَهُم مِّن جُوعٍ وَآمَنَهُم مِّنْ خَوْفٍ", transliteration: "Alladhī aṭ'amahum min jū'in wa āmanahum min khawf", translation: "Who has fed them, saving them from hunger, and made them safe, saving them from fear" },
  // Al-Fil (105) - 5 verses
  { surahNum: 105, ayahNum: 1, arabic: "أَلَمْ تَرَ كَيْفَ فَعَلَ رَبُّكَ بِأَصْحَابِ الْفِيلِ", transliteration: "Alam tara kayfa fa'ala rabbuka bi-aṣḥābi l-fīl", translation: "Have you not considered how your Lord dealt with the companions of the elephant?" },
  { surahNum: 105, ayahNum: 2, arabic: "أَلَمْ يَجْعَلْ كَيْدَهُمْ فِي تَضْلِيلٍ", transliteration: "Alam yaj'al kaydahum fī taḍlīl", translation: "Did He not make their plan into misguidance?" },
  { surahNum: 105, ayahNum: 3, arabic: "وَأَرْسَلَ عَلَيْهِمْ طَيْرًا أَبَابِيلَ", transliteration: "Wa arsala 'alayhim ṭayran abābīl", translation: "And He sent against them birds in flocks" },
  { surahNum: 105, ayahNum: 4, arabic: "تَرْمِيهِم بِحِجَارَةٍ مِّن سِجِّيلٍ", transliteration: "Tarmīhim biḥijāratin min sijjīl", translation: "Striking them with stones of hard clay" },
  { surahNum: 105, ayahNum: 5, arabic: "فَجَعَلَهُمْ كَعَصْفٍ مَّأْكُولٍ", transliteration: "Faja'alahum ka'aṣfin ma'kūl", translation: "And He made them like eaten straw" },
] as const;

export type VerseEntry = typeof JUZ30_VERSES[number];