export interface AdhkarItem {
  key: string;
  arabic: string;
  transliteration: string;
  translation: string;
  count: number; // target repetitions
  benefit?: string;
}

export const MORNING_ADHKAR: AdhkarItem[] = [
  {
    key: "morning_1",
    arabic: "أَصْبَحْنَا وَأَصْبَحَ الْمُلْكُ لِلَّهِ، وَالْحَمْدُ لِلَّهِ، لاَ إِلَهَ إِلاَّ اللَّهُ وَحْدَهُ لاَ شَرِيكَ لَهُ",
    transliteration: "Asbahna wa asbahal mulku lillah...",
    translation: "We have reached the morning and the whole kingdom belongs to Allah. All praise is for Allah. None has the right to be worshipped except Allah, alone, without partner.",
    count: 1,
  },
  {
    key: "morning_2",
    arabic: "اللَّهُمَّ بِكَ أَصْبَحْنَا، وَبِكَ أَمْسَيْنَا، وَبِكَ نَحْيَا، وَبِكَ نَمُوتُ وَإِلَيْكَ النُّشُورُ",
    transliteration: "Allahumma bika asbahna...",
    translation: "O Allah, by You we enter the morning and by You we enter the evening, by You we live and by You we die, and to You is the resurrection.",
    count: 1,
  },
  {
    key: "morning_3",
    arabic: "اللَّهُمَّ أَنْتَ رَبِّي لاَ إِلَهَ إِلاَّ أَنْتَ، خَلَقْتَنِي وَأَنَا عَبْدُكَ",
    transliteration: "Allahumma anta rabbi la ilaha illa ant...",
    translation: "O Allah, You are my Lord. None has the right to be worshipped except You. You created me and I am Your servant.",
    count: 1,
    benefit: "Sayyid al-Istighfar — best supplication for forgiveness",
  },
  {
    key: "morning_4",
    arabic: "سُبْحَانَ اللَّهِ وَبِحَمْدِهِ",
    transliteration: "Subhanallahi wa bihamdihi",
    translation: "Glory be to Allah and praise Him.",
    count: 100,
    benefit: "Wipes away sins even if they are like the foam of the sea",
  },
  {
    key: "morning_5",
    arabic: "لاَ إِلَهَ إِلاَّ اللَّهُ وَحْدَهُ لاَ شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ",
    transliteration: "La ilaha illallahu wahdahu la sharika lah...",
    translation: "None has the right to be worshipped except Allah, alone, without partner. To Him belongs the dominion and all praise, and He is over all things competent.",
    count: 100,
    benefit: "Equivalent to freeing 4 slaves, 10 good deeds written, 10 sins erased",
  },
  {
    key: "morning_6",
    arabic: "اللَّهُمَّ إِنِّي أَسْأَلُكَ الْعَافِيَةَ فِي الدُّنْيَا وَالآخِرَةِ",
    transliteration: "Allahumma inni as'alukal afiyah...",
    translation: "O Allah, I ask You for wellbeing in this world and the Hereafter.",
    count: 1,
  },
  {
    key: "morning_7",
    arabic: "اللَّهُمَّ عَافِنِي فِي بَدَنِي، اللَّهُمَّ عَافِنِي فِي سَمْعِي، اللَّهُمَّ عَافِنِي فِي بَصَرِي",
    transliteration: "Allahumma afini fi badani...",
    translation: "O Allah, grant me health in my body. O Allah, grant me health in my hearing. O Allah, grant me health in my sight.",
    count: 3,
  },
  {
    key: "morning_8",
    arabic: "حَسْبِيَ اللَّهُ لاَ إِلَهَ إِلاَّ هُوَ عَلَيْهِ تَوَكَّلْتُ وَهُوَ رَبُّ الْعَرْشِ الْعَظِيمِ",
    transliteration: "Hasbiyallahu la ilaha illa huwa...",
    translation: "Allah is sufficient for me. None has the right to be worshipped except Him. Upon Him I rely and He is Lord of the Mighty Throne.",
    count: 7,
    benefit: "Whoever says this 7 times, Allah will suffice him in worldly and religious affairs",
  },
  {
    key: "morning_9",
    arabic: "بِسْمِ اللَّهِ الَّذِي لاَ يَضُرُّ مَعَ اسْمِهِ شَيْءٌ فِي الأَرْضِ وَلاَ فِي السَّمَاءِ وَهُوَ السَّمِيعُ الْعَلِيمُ",
    transliteration: "Bismillahilladhi la yadurru ma'asmihi shay'...",
    translation: "In the name of Allah, with whose name nothing can cause harm on earth or in heaven, and He is the All-Hearing, All-Knowing.",
    count: 3,
    benefit: "Nothing will harm him",
  },
  {
    key: "morning_10",
    arabic: "رَضِيتُ بِاللَّهِ رَبًّا، وَبِالإِسْلاَمِ دِينًا، وَبِمُحَمَّدٍ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ نَبِيًّا",
    transliteration: "Raditu billahi rabba, wa bil-Islami dinan...",
    translation: "I am pleased with Allah as my Lord, Islam as my religion, and Muhammad (peace be upon him) as my Prophet.",
    count: 3,
    benefit: "Allah will please him on the Day of Judgement",
  },
  {
    key: "morning_11",
    arabic: "يَا حَيُّ يَا قَيُّومُ بِرَحْمَتِكَ أَسْتَغِيثُ أَصْلِحْ لِي شَأْنِي كُلَّهُ وَلاَ تَكِلْنِي إِلَى نَفْسِي طَرْفَةَ عَيْنٍ",
    transliteration: "Ya Hayyu Ya Qayyumu birahmatika astaghith...",
    translation: "O Ever-Living, O Sustainer, by Your mercy I seek relief. Correct for me all of my affairs and do not leave me to rely on myself for even a blink of an eye.",
    count: 1,
  },
  {
    key: "morning_12",
    arabic: "أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ",
    transliteration: "A'udhu bikalimatillahit-tammati min sharri ma khalaq",
    translation: "I seek refuge in the perfect words of Allah from the evil of what He has created.",
    count: 3,
    benefit: "Nothing will harm him that evening",
  },
];

export const EVENING_ADHKAR: AdhkarItem[] = [
  {
    key: "evening_1",
    arabic: "أَمْسَيْنَا وَأَمْسَى الْمُلْكُ لِلَّهِ، وَالْحَمْدُ لِلَّهِ، لاَ إِلَهَ إِلاَّ اللَّهُ وَحْدَهُ لاَ شَرِيكَ لَهُ",
    transliteration: "Amsayna wa amsal mulku lillah...",
    translation: "We have reached the evening and the whole kingdom belongs to Allah. All praise is for Allah. None has the right to be worshipped except Allah, alone, without partner.",
    count: 1,
  },
  {
    key: "evening_2",
    arabic: "اللَّهُمَّ بِكَ أَمْسَيْنَا، وَبِكَ أَصْبَحْنَا، وَبِكَ نَحْيَا، وَبِكَ نَمُوتُ وَإِلَيْكَ الْمَصِيرُ",
    transliteration: "Allahumma bika amsayna...",
    translation: "O Allah, by You we enter the evening and by You we enter the morning, by You we live and by You we die, and to You is the final return.",
    count: 1,
  },
  {
    key: "evening_3",
    arabic: "اللَّهُمَّ أَنْتَ رَبِّي لاَ إِلَهَ إِلاَّ أَنْتَ، خَلَقْتَنِي وَأَنَا عَبْدُكَ",
    transliteration: "Allahumma anta rabbi...",
    translation: "O Allah, You are my Lord. None has the right to be worshipped except You. You created me and I am Your servant.",
    count: 1,
    benefit: "Sayyid al-Istighfar",
  },
  {
    key: "evening_4",
    arabic: "سُبْحَانَ اللَّهِ وَبِحَمْدِهِ",
    transliteration: "Subhanallahi wa bihamdihi",
    translation: "Glory be to Allah and praise Him.",
    count: 100,
  },
  {
    key: "evening_5",
    arabic: "لاَ إِلَهَ إِلاَّ اللَّهُ وَحْدَهُ لاَ شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ",
    transliteration: "La ilaha illallahu wahdahu...",
    translation: "None has the right to be worshipped except Allah, alone, without partner.",
    count: 10,
  },
  {
    key: "evening_6",
    arabic: "اللَّهُمَّ إِنِّي أَمْسَيْتُ أُشْهِدُكَ وَأُشْهِدُ حَمَلَةَ عَرْشِكَ وَمَلاَئِكَتَكَ وَجَمِيعَ خَلْقِكَ",
    transliteration: "Allahumma inni amsaytu ushhiduka...",
    translation: "O Allah, I have reached the evening and call on You, the bearers of Your Throne, Your angels and all of Your creation to witness that You are Allah, none has the right to be worshipped except You, alone, without partner.",
    count: 4,
    benefit: "Allah will free a quarter of him from Hellfire for each time",
  },
  {
    key: "evening_7",
    arabic: "اللَّهُمَّ عَافِنِي فِي بَدَنِي، اللَّهُمَّ عَافِنِي فِي سَمْعِي، اللَّهُمَّ عَافِنِي فِي بَصَرِي",
    transliteration: "Allahumma afini fi badani...",
    translation: "O Allah, grant me health in my body. O Allah, grant me health in my hearing. O Allah, grant me health in my sight.",
    count: 3,
  },
  {
    key: "evening_8",
    arabic: "حَسْبِيَ اللَّهُ لاَ إِلَهَ إِلاَّ هُوَ عَلَيْهِ تَوَكَّلْتُ وَهُوَ رَبُّ الْعَرْشِ الْعَظِيمِ",
    transliteration: "Hasbiyallahu la ilaha illa huwa...",
    translation: "Allah is sufficient for me.",
    count: 7,
  },
  {
    key: "evening_9",
    arabic: "بِسْمِ اللَّهِ الَّذِي لاَ يَضُرُّ مَعَ اسْمِهِ شَيْءٌ فِي الأَرْضِ وَلاَ فِي السَّمَاءِ",
    transliteration: "Bismillahilladhi la yadurru...",
    translation: "In the name of Allah, with whose name nothing can cause harm on earth or in heaven.",
    count: 3,
  },
  {
    key: "evening_10",
    arabic: "أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ",
    transliteration: "A'udhu bikalimatillahit-tammati...",
    translation: "I seek refuge in the perfect words of Allah from the evil of what He has created.",
    count: 3,
  },
  {
    key: "evening_11",
    arabic: "اللَّهُمَّ إِنِّي أَسْأَلُكَ الْعَفْوَ وَالْعَافِيَةَ فِي الدُّنْيَا وَالآخِرَةِ",
    transliteration: "Allahumma inni as'alukal afwa wal afiyah...",
    translation: "O Allah, I ask You for pardon and wellbeing in this world and the Hereafter.",
    count: 1,
  },
  {
    key: "evening_12",
    arabic: "اللَّهُمَّ فَاطِرَ السَّمَوَاتِ وَالأَرْضِ، عَالِمَ الْغَيْبِ وَالشَّهَادَةِ، أَنْتَ رَبُّ كُلِّ شَيْءٍ",
    transliteration: "Allahumma fatiras samawati wal ard...",
    translation: "O Allah, Creator of the heavens and earth, Knower of the seen and unseen, Lord of all things.",
    count: 1,
  },
];

export const BEFORE_SLEEP_ADHKAR: AdhkarItem[] = [
  {
    key: "sleep_1",
    arabic: "بِسْمِكَ اللَّهُمَّ أَمُوتُ وَأَحْيَا",
    transliteration: "Bismika Allahumma amutu wa ahya",
    translation: "In Your name, O Allah, I die and I live.",
    count: 1,
  },
  {
    key: "sleep_2",
    arabic: "الْحَمْدُ لِلَّهِ الَّذِي أَطْعَمَنَا وَسَقَانَا وَكَفَانَا وَآوَانَا",
    transliteration: "Alhamdu lillahilladhi at'amana wa saqana...",
    translation: "All praise is for Allah who fed us, gave us drink, satisfied us, and gave us shelter.",
    count: 1,
  },
  {
    key: "sleep_3",
    arabic: "اللَّهُمَّ قِنِي عَذَابَكَ يَوْمَ تَبْعَثُ عِبَادَكَ",
    transliteration: "Allahumma qini adhabaka yawma tab'athu ibadak",
    translation: "O Allah, protect me from Your punishment on the Day You resurrect Your servants.",
    count: 3,
  },
  {
    key: "sleep_4",
    arabic: "بِاسْمِكَ رَبِّي وَضَعْتُ جَنْبِي، وَبِكَ أَرْفَعُهُ",
    transliteration: "Bismika rabbi wada'tu janbi wa bika arfa'uh",
    translation: "In Your name my Lord, I lie down and in Your name I rise.",
    count: 1,
  },
  {
    key: "sleep_5",
    arabic: "اللَّهُمَّ إِنَّكَ خَلَقْتَ نَفْسِي وَأَنْتَ تَوَفَّاهَا",
    transliteration: "Allahumma innaka khalaqta nafsi wa anta tawaffaha",
    translation: "O Allah, You created my soul and You take it back.",
    count: 1,
  },
  {
    key: "sleep_6",
    arabic: "سُبْحَانَ اللَّهِ",
    transliteration: "Subhanallah",
    translation: "Glory be to Allah.",
    count: 33,
    benefit: "Sunnah tasbeeh before sleep",
  },
  {
    key: "sleep_7",
    arabic: "الْحَمْدُ لِلَّهِ",
    transliteration: "Alhamdulillah",
    translation: "All praise is for Allah.",
    count: 33,
  },
  {
    key: "sleep_8",
    arabic: "اللَّهُ أَكْبَرُ",
    transliteration: "Allahu Akbar",
    translation: "Allah is the Greatest.",
    count: 34,
    benefit: "Better for you than a servant",
  },
  {
    key: "sleep_9",
    arabic: "آيَةُ الْكُرْسِيِّ",
    transliteration: "Ayatul Kursi — Allahu la ilaha illa huwal hayyul qayyum...",
    translation: "Ayatul Kursi (2:255) — recite once before sleeping.",
    count: 1,
    benefit: "A guardian from Allah protects you until morning, and Shaytan cannot approach you",
  },
  {
    key: "sleep_10",
    arabic: "قُلْ هُوَ اللَّهُ أَحَدٌ — قُلْ أَعُوذُ بِرَبِّ الْفَلَقِ — قُلْ أَعُوذُ بِرَبِّ النَّاسِ",
    transliteration: "Al-Ikhlas, Al-Falaq, An-Nas",
    translation: "Recite Surah Al-Ikhlas, Al-Falaq, and An-Nas — blow into cupped hands and wipe over body 3 times.",
    count: 3,
    benefit: "Sufficient for everything",
  },
];
